### ISSUE TITLE
File paths/directories too long (Windows)

### ISSUE THREAD

**Issue by shadowimmage** [uw-it-aca/uw-restclients-sws#98]
Files in the directory `uw_sws/resources/sws/file/student/v5/` are very long, so long that they cannot be cloned / created on a Windows-based machine, as they exceed the maximum path/filename length.

Attempting to clone this repository leads to a long series of errors on Windows:

> $ git clone git@github.com:uw-it-aca/uw-restclients-sws.git                                                                                                                                                                    Cloning into 'uw-restclients-sws'...                                                                                                                                                                                           remote: Enumerating objects: 2442, done.                                                                                                                                                                                       Rremote: Total 2442 (delta 0), reused 0 (delta 0), pack-reused 2442                                                                                                                                                            Receiving objects: 100% (2442/2442), 497.90 KiB \| 5.08 MiB/s, done.                                                                                                                                                            Resolving deltas: 100% (1579/1579), done.                                                                                                                                                                                      error: unable to create file uw_sws/resources/sws/file/student/v5/registration.json_curriculum_abbreviation_DROP_T_instructor_reg_id__course_number_100_verbose_true_year_2013_quarter_winter_is_active__section_id_B_transcri ptable_course_all: Filename too long                                                                                                                                                                                           error: unable to create file uw_sws/resources/sws/file/student/v5/registration.json_curriculum_abbreviation_EDC_I_instructor_reg_id__course_number_552_verbose_true_year_2017_quarter_autumn_is_active_true_section_id_A_trans criptable_course_all: Filename too long                                                                                                                                                                                        error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_260A0DEC95CB11D78BAA000629C31437_search_by_Instructor_quarter_autumn_include_secondaries__year_2012_future_terms_4_transcriptable_course _all_delete_flag_active: Filename too long                                                                                                                                                                                     error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_260A0DEC95CB11D78BAA000629C31437_search_by_Instructor_quarter_spring_include_secondaries__year_2013_future_terms_2_transcriptable_course _all_delete_flag_active: Filename too long                                                                                                                                                                                     error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_260A0DEC95CB11D78BAA000629C31437_search_by_Instructor_quarter_spring_include_secondaries_on_year_2013_future_terms_0_transcriptable_cour se_all_delete_flag_active: Filename too long                                                                                                                                                                                   error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_FBB38FE46A7C11D5A4AE0004AC494FFE_search_by_GradeSubmissionDelegate_quarter_spring_include_secondaries_on_year_2013_future_terms_0_transc riptable_course_yes_delete_flag_active: Filename too long                                                                                                                                                                      error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_FBB38FE46A7C11D5A4AE0004AC494FFE_search_by_GradeSubmissionDelegate_quarter_summer_include_secondaries_on_year_2013_future_terms_0_transc riptable_course_yes_delete_flag_active: Filename too long                                                                                                                                                                      error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_FBB38FE46A7C11D5A4AE0004AC494FFE_search_by_GradeSubmissionDelegate_quarter_summer_include_secondaries_on_year_2013_future_terms_0_transc riptable_course_yes_delete_flag_active_suspended: Filename too long                                                                                                                                                            error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_FBB38FE46A7C11D5A4AE0004AC494FFE_search_by_Instructor_quarter_spring_include_secondaries_on_year_2013_future_terms_0_transcriptable_cour se_yes_delete_flag_active: Filename too long                                                                                                                                                                                   error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_FBB38FE46A7C11D5A4AE0004AC494FFE_search_by_Instructor_quarter_spring_include_secondaries_on_year_2013_future_terms_0_transcriptable_cour se_yes_delete_flag_active_suspended: Filename too long                                                                                                                                                                         error: unable to create file uw_sws/resources/sws/file/student/v5/section.json_reg_id_FBB38FE46A7C11D5A4AE0004AC494FFE_search_by_Instructor_quarter_summer_include_secondaries_on_year_2013_future_terms_0_transcriptable_cour se_yes_delete_flag_active: Filename too long                                                                                                                                                                                   fatal: unable to checkout working tree                                                                                                                                                                                         warning: Clone succeeded, but checkout failed.                                                                                                                                                                                 You can inspect what was checked out with 'git status'                                                                                                                                                                         and retry the checkout with 'git checkout -f HEAD'
--

This also creates problems for any project that relies on this repository as a dependency.

Is it possible that these could be shortened?

**Comment by jlaney** [comment]
These file paths are just platform-safe versions of actual SWS section search URLs, and are used by the unit tests.  Renaming them to something other than what the client is requesting would not be a simple modification.

Is it possible to enable the 'LongPathsEnabled' registry setting in your Windows environment?

**Comment by shadowimmage** [comment]
I have long paths enabled, but it seems that git, mingw64, git-bash for Windows, or something else involved in the file creation doesn't support the long paths option. When I'm back tomorrow I'll look into what I can do to get around this.
For instance the Linux Subsystem for Windows is able to handle it fine in it's native filesystem, but cloning into a symlinked folder within Windows fails.

**Comment by shadowimmage** [comment]
I looked into it more, and there seem to be some workarounds, but they're all kinda weird. It turned out to be faster and easier to simply setup an Ubuntu 18.04 environment in Hyper-V instead, so I can actually get something done rather than fight with Windows about the filename lengths.

**Comment by jlaney** [comment]
Glad you found a workaround.
